
[dependencies]
  fastly = "^0.8.5"
  serde = "1.0.140"
  base64 = "0.13.0"
  handlebars = "4.3.0"
  serde_json = "1.0.81"

[package]
  authors = []
  edition = "2018"
  name = "fanout-play"
  publish = false
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
